theme: jekyll-theme-minimal
title: Video games during Covid lockdown
description: Analysis of the evolution of interest in video games during the covid period
show_downloads: True
navigation:
  - title: Example
    url: example
  - title: Lockdown Intensity
    url: example
