remote_theme: "pages-themes/cayman@v0.5.1"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-cayman
title: Video games during Covid lockdown
description: Analysis of the evolution of interest in video games during the covid period
show_downloads: False
navigation:
  - title: Relation mobility/interest
    url: Relation_mobility_pages
